"""Canonical release identity used by runtime code and QA."""

SOFTWARE_NAME = "ROBO_DADOS_PUBLICOS_SOFTWARE_V01"
SOFTWARE_VERSION = "0.6.3"
RELEASE_STATUS = "CANDIDATE"
ACTIVE_VALIDATED_VERSION = "0.6.2"
CURRENT_CANDIDATE_VERSION = SOFTWARE_VERSION
METHOD_VERSION = "V17"
NEXT_ACTION = "M4F_RUN_OBSERVABILITY_GATE_AND_REVIEW_OPERATOR_REPORT"

USER_AGENT = f"ROBO_DADOS_PUBLICOS/{SOFTWARE_VERSION}"
RESEARCH_USER_AGENT = f"{USER_AGENT} (+public-transparency-research)"
