"""Canonical release identity used by runtime code and QA."""

SOFTWARE_NAME = "ROBO_DADOS_PUBLICOS_SOFTWARE_V01"
SOFTWARE_VERSION = "0.7.0"
RELEASE_STATUS = "ACTIVE"
ACTIVE_VALIDATED_VERSION = SOFTWARE_VERSION
CURRENT_CANDIDATE_VERSION = "NONE"
METHOD_VERSION = "V17"
NEXT_ACTION = "M7_CONTROLLED_SOURCE_EXPANSION_DESIGN_0_8_0"

USER_AGENT = f"ROBO_DADOS_PUBLICOS/{SOFTWARE_VERSION}"
RESEARCH_USER_AGENT = f"{USER_AGENT} (+public-transparency-research)"
