"""Canonical release identity used by runtime code and QA."""

SOFTWARE_NAME = "ROBO_DADOS_PUBLICOS_SOFTWARE_V01"
SOFTWARE_VERSION = "0.7.0"
RELEASE_STATUS = "CANDIDATE"
ACTIVE_VALIDATED_VERSION = "0.6.3"
CURRENT_CANDIDATE_VERSION = SOFTWARE_VERSION
METHOD_VERSION = "V17"
NEXT_ACTION = "M6_PRODUCT_OUTPUT_CONTROLLED_PUBLICATION_GATE_0_7_0"

USER_AGENT = f"ROBO_DADOS_PUBLICOS/{SOFTWARE_VERSION}"
RESEARCH_USER_AGENT = f"{USER_AGENT} (+public-transparency-research)"
