from typing import Protocol, Iterable
from pathlib import Path

class StorageBackend(Protocol):
    def put(self, local_path: str | Path, remote_name: str, parent_id: str | None = None) -> dict: ...
    def get(self, file_id: str, destination: str | Path) -> dict: ...
    def list_children(self, parent_id: str) -> list[dict]: ...
